ARG runtime=python3.11

FROM python:3.11 AS build

WORKDIR /operator-build

ADD aws-opentelemetry-distro/ ./aws-opentelemetry-distro/

# Remove opentelemetry-exporter-otlp-proto-grpc and grpcio, as grpcio has strict dependencies on the Python version and
# will cause confusing failures if gRPC protocol is used. Now if gRPC protocol is requested by the user, instrumentation
# will complain that grpc is not installed, which is more understandable. References:
# * https://github.com/open-telemetry/opentelemetry-operator/blob/b5bb0ae34720d4be2d229dafecb87b61b37699b0/autoinstrumentation/python/requirements.txt#L2
# * https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/azure-functions/recover-python-functions.md#troubleshoot-cannot-import-cygrpc
RUN sed -i "/opentelemetry-exporter-otlp-proto-grpc/d" ./aws-opentelemetry-distro/pyproject.toml

RUN mkdir workspace && pip install --target workspace ./aws-opentelemetry-distro

FROM public.ecr.aws/sam/build-${runtime}

ADD . /workspace

WORKDIR /workspace

RUN mkdir -p /build/python

COPY --from=build /operator-build/workspace /build/python

RUN mv lambda-layer/otel/otel_sdk/otel_wrapper.py /build/python && \
    mv lambda-layer/otel/otel_sdk/otel-instrument /build && \
    chmod 755 /build/otel-instrument && \
    rm -rf /build/python/boto* && \
    rm -rf /build/python/urllib3* && \
    cd /build && \
    zip -r opentelemetry-python-layer-1.zip otel-instrument python

CMD cp /build/opentelemetry-python-layer-1.zip /out/opentelemetry-python-layer.zip
